# Generated by Django 4.2.3 on 2023-07-26 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('image', models.ImageField(blank=True, help_text='Загрузите картинку для категории', null=True, upload_to='')),
                ('category_slug', models.SlugField(default='', help_text='Перед вводом названия категории очистите это поле', unique=True, verbose_name='URl')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название товара')),
                ('product_slug', models.SlugField(default='', help_text='Перед вводом названия продукта очистите это поле', max_length=100, unique=True, verbose_name='URl')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка товара')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену', max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Цена со скидкой')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('is_hit', models.BooleanField(default=False, verbose_name='Хит товар')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Акционный товар')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Кол-во товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name', 'product_slug'),
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название подкатегории')),
                ('image', models.ImageField(blank=True, help_text='Загрузите картинку для категории', null=True, upload_to='')),
                ('subcategory_slug', models.SlugField(default='', help_text='Перед вводом названия категории очистите это поле', unique=True, verbose_name='URl')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
