# Generated by Django 4.2.3 on 2023-08-09 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sale',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку для подкатегории', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_slug',
            field=models.SlugField(default='', help_text='Перед вводом названия подкатегории очистите это поле', unique=True, verbose_name='URl'),
        ),
        migrations.CreateModel(
            name='SecondSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название второй подкатегории')),
                ('image', models.ImageField(blank=True, help_text='Загрузите картинку для подподкатегории', null=True, upload_to='')),
                ('second_subcategory_slug', models.SlugField(default='', help_text='Перед вводом названия второй подкатегории очистите это поле', unique=True, verbose_name='URl')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Категория')),
                ('subcategories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Вторая Подкатегория',
                'verbose_name_plural': 'Вторые Подкатегории',
            },
        ),
    ]
