# Generated by Django 4.2.3 on 2023-07-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Комментарий к продукту')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.flowers')),
            ],
        ),
    ]
