# Generated by Django 4.2.3 on 2023-08-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название филиала')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('min_volume', models.PositiveIntegerField()),
                ('max_volume', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорты',
            },
        ),
        migrations.CreateModel(
            name='TypeOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип заказа',
                'verbose_name_plural': 'Типы заказа',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('as_soon_as_possible', models.BooleanField(default=False, verbose_name='Как можно скорее')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания заказа')),
                ('order_date_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата и время забора заказа')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('apartment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дом/квартира')),
                ('floor_and_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Этаж и код от домофона')),
                ('additional_to_order', models.CharField(blank=True, max_length=200, null=True, verbose_name='Доп инфо к заказу')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.filial', verbose_name='Филиал')),
                ('type_of_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.typeoforder', verbose_name='Вид заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
