# Generated by Django 4.2.3 on 2023-07-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_description', models.TextField(max_length=150)),
                ('image', models.ImageField(default='static/gloria.jpg', upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
