# Generated by Django 4.2.3 on 2023-08-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_is_sale_alter_subcategory_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Картинка товара №1', null=True, upload_to='', verbose_name='Картинка товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Картинка товара №2', null=True, upload_to='', verbose_name='Картинка товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Картинка товара №3', null=True, upload_to='', verbose_name='Картинка товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Картинка товара №4', null=True, upload_to='', verbose_name='Картинка товара'),
        ),
    ]
