# Generated by Django 4.2.3 on 2023-09-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_transaction_order'),
        ('product', '0003_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type_of_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Filial',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='TypeOfOrder',
        ),
    ]
