# Generated by Django 4.2.3 on 2023-07-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_stories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='title_description',
        ),
    ]
