# Generated by Django 4.2.3 on 2023-08-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_image_product_image_1_product_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='second_subcategories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.secondsubcategory', verbose_name='Вторая подкатегория товара'),
        ),
    ]
