# Generated by Django 4.2.3 on 2023-07-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'product_slug'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(default='', help_text='Перед вводом названия категории очистите это поле', unique=True, verbose_name='URl'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку для категории', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=100, unique=True, verbose_name='Название товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(default='', help_text='Перед вводом названия продукта очистите это поле', max_length=100, unique=True, verbose_name='URl'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку для категории', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_slug',
            field=models.SlugField(default='', help_text='Перед вводом названия категории очистите это поле', unique=True, verbose_name='URl'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Введите цену', max_digits=10),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'product_slug')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
