# Generated by Django 4.2.3 on 2023-08-23 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='product.category', verbose_name='Категория'),
        ),
    ]
