# Generated by Django 4.2.3 on 2023-09-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_balls_balls_size_alter_balls_is_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balls',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.DeleteModel(
            name='BallsPrice',
        ),
    ]
