# Generated by Django 4.2.3 on 2023-09-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_balls_product_remove_postcard_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balls',
            name='price',
        ),
        migrations.AddField(
            model_name='fontsize',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='price'),
            preserve_default=False,
        ),
    ]
