# Generated by Django 4.2.3 on 2023-09-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_balls_price_fontsize_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcard',
            name='is_cart',
        ),
    ]
