# Generated by Django 4.2.3 on 2023-08-08 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_subcategory_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
