# Generated by Django 4.2.3 on 2023-09-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_order_filial_remove_order_transport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcard',
            name='product',
        ),
        migrations.RemoveField(
            model_name='titleonball',
            name='product',
        ),
    ]
