# Generated by Django 4.2.3 on 2023-09-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_balls_price_delete_ballsprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balls',
            name='price',
        ),
        migrations.AddField(
            model_name='fontsize',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
