# Generated by Django 4.2.3 on 2023-07-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_stories_title_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quationsanswers',
            options={'verbose_name': 'Вопросы-Ответы', 'verbose_name_plural': 'Вопросы-Ответы'},
        ),
        migrations.AlterModelOptions(
            name='stories',
            options={'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
    ]
