# Generated by Django 4.2.3 on 2023-08-11 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена открытки')),
            ],
        ),
        migrations.CreateModel(
            name='PostCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст на открытке для букетов')),
                ('is_cart', models.BooleanField(blank=True, default=False, null=True, verbose_name='Добавление открытки к букету')),
                ('price', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.postcardprice', verbose_name='Цена открытки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
            ],
        ),
    ]
