# Generated by Django 4.2.3 on 2023-09-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_postcard_is_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='text',
            field=models.CharField(default=2, max_length=100, verbose_name='Текст на открытке для букетов'),
            preserve_default=False,
        ),
    ]
