# Generated by Django 4.2.3 on 2023-09-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_balls_price_fontsize_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balls',
            name='product',
        ),
        migrations.AddField(
            model_name='balls',
            name='user_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт пользователя'),
            preserve_default=False,
        ),
    ]
