# Generated by Django 4.2.3 on 2023-09-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_postcard_product_remove_titleonball_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='price',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to='product.postcardprice', verbose_name='Цена открытки'),
        ),
        migrations.AlterField(
            model_name='titleonball',
            name='size',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='product.fontsize', verbose_name='Размер шрифта'),
        ),
    ]
