# Generated by Django 4.2.3 on 2023-08-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_subcategory_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('min_volume', models.PositiveIntegerField()),
                ('max_volume', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
