# Generated by Django 4.2.3 on 2023-07-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
    ]
