# Generated by Django 4.2.3 on 2023-09-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_postcard_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='product_quantity',
        ),
    ]
