# Generated by Django 4.2.3 on 2023-09-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_postcard_price_alter_titleonball_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleonball',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
    ]
