# Generated by Django 4.2.3 on 2023-08-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_transport_product_volume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспорты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Введите цену', max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='max_volume',
            field=models.PositiveIntegerField(verbose_name='Максимальное значение'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='min_volume',
            field=models.PositiveIntegerField(verbose_name='Минимальнео значение'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель транспорта'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
