# Generated by Django 4.2.3 on 2023-08-08 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='Размер шрифта')),
            ],
        ),
        migrations.CreateModel(
            name='PostCardForFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Надпись на открытке')),
                ('price', models.IntegerField(default=25, verbose_name='Цена открытки')),
            ],
        ),
        migrations.CreateModel(
            name='TitleOnBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Надпись на шаре')),
                ('font_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.fontsize', verbose_name='Размер шрифта')),
            ],
        ),
    ]
