# Generated by Django 4.2.3 on 2023-08-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_postcardprice_postcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='is_cart',
            field=models.BooleanField(default=False, verbose_name='Добавление открытки к букету'),
        ),
    ]
