# Generated by Django 4.2.3 on 2023-09-15 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_quantity_product_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balls',
            name='product',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='product',
        ),
        migrations.AddField(
            model_name='balls',
            name='cart_items_balls',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='cart_items_balls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcard',
            name='cart_item_postcard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='post_card_product'),
            preserve_default=False,
        ),
    ]
