# Generated by Django 4.2.3 on 2023-08-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_transport_options_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='price',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='product.postcardprice', verbose_name='Цена открытки'),
        ),
    ]
