# Generated by Django 4.2.3 on 2023-09-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_balls_product_remove_postcard_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balls',
            name='cart_items_balls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='cart_items_balls'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='cart_item_postcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='post_card_product'),
        ),
    ]
