# Generated by Django 4.2.3 on 2023-07-31 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_added_text_product_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='text',
        ),
    ]
