# Generated by Django 4.2.3 on 2023-09-06 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_postcard_product_postcardprice_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcardprice',
            name='product',
        ),
        migrations.AddField(
            model_name='titleonball',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
    ]
