# Generated by Django 4.2.3 on 2023-08-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_fontsize_titleonball'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fontsize',
            options={'verbose_name': 'Размеры Надписи', 'verbose_name_plural': 'Размеры Надписи'},
        ),
        migrations.AlterModelOptions(
            name='postcard',
            options={'verbose_name': 'Открытка', 'verbose_name_plural': 'Открытка'},
        ),
        migrations.AlterModelOptions(
            name='postcardprice',
            options={'verbose_name': 'Цена открыток', 'verbose_name_plural': 'Цена открыток'},
        ),
        migrations.AlterModelOptions(
            name='titleonball',
            options={'verbose_name': 'Надпись на Шаре', 'verbose_name_plural': 'Надпись на Шаре'},
        ),
    ]
