# Generated by Django 4.2.3 on 2023-09-17 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_alter_balls_cart_items_balls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balls',
            name='is_cart',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Добавление надписи к шару'),
        ),
        migrations.AlterField(
            model_name='balls',
            name='size',
            field=models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.fontsize', verbose_name='Размер шрифта'),
        ),
        migrations.AlterField(
            model_name='balls',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='price',
            field=models.ForeignKey(blank=True, default=25, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.postcardprice', verbose_name='Цена открытки'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст на открытке для букетов'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
