# Generated by Django 4.2.3 on 2023-09-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_balls_is_cart_alter_balls_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображение'},
        ),
    ]
