# Generated by Django 4.2.3 on 2023-08-18 15:31

import apps.product.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_image_1_remove_product_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку для категории', null=True, upload_to=apps.product.utils.path_and_rename2),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to=apps.product.utils.path_and_rename),
        ),
        migrations.AlterField(
            model_name='secondsubcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку для подподкатегории', null=True, upload_to=apps.product.utils.path_and_rename4),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку для подкатегории', null=True, upload_to=apps.product.utils.path_and_rename3),
        ),
    ]
