# Generated by Django 4.2.3 on 2023-09-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_imagemodel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balls',
            old_name='size',
            new_name='balls_size',
        ),
    ]
