# Generated by Django 4.2.3 on 2023-09-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_size_balls_balls_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
            ],
            options={
                'verbose_name': 'Цена шара',
                'verbose_name_plural': 'Цена шара',
            },
        ),
        migrations.RemoveField(
            model_name='fontsize',
            name='price',
        ),
        migrations.AddField(
            model_name='balls',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ballsprice'),
        ),
    ]
