# Generated by Django 4.2.3 on 2023-09-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_ballsprice_remove_fontsize_price_balls_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balls',
            old_name='cart_items_balls',
            new_name='product',
        ),
    ]
