# Generated by Django 4.2.3 on 2023-09-29 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Баннеры',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balls', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('postcards', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, unique=True, verbose_name='ID админа')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('bot_owner', models.BooleanField(default=False, verbose_name='Владелец бота')),
            ],
            options={
                'verbose_name': 'Админ телеграм',
                'verbose_name_plural': 'Админ телеграма',
            },
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_address', models.CharField(max_length=150, verbose_name='Название филиала')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date_time', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата и время забора заказа')),
                ('person_name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('type_of_order', models.CharField(choices=[('Доставка', 'Доставка'), ('Самовывоз', 'Самовывоз')], max_length=100, verbose_name='Тип заказа')),
                ('as_soon_as_possible', models.BooleanField(default=False, verbose_name='Как можно скорее')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания заказа')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('apartment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дом/квартира')),
                ('floor_and_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Этаж и код от домофона')),
                ('additional_to_order', models.CharField(blank=True, max_length=200, null=True, verbose_name='Доп инфо к заказу')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('status_order', models.CharField(blank=True, choices=[('Отменено', 'Отменено'), ('Доставлено', 'Доставлено'), ('В Обработке', 'В Обработке')], max_length=140, null=True)),
                ('total_cart_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('filial', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cart.filial')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
