# Generated by Django 4.2.3 on 2023-08-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_banners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name': 'Баннеры', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterField(
            model_name='banners',
            name='link',
            field=models.CharField(default='http://127.0.0.1:8000/api/v1/categories/', max_length=50),
        ),
    ]
