# Generated by Django 4.2.3 on 2023-08-17 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banners',
            name='category_id',
            field=models.CharField(max_length=700, verbose_name='<property object at 0x0000016E0F711DA0>'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='cart.cartitem', verbose_name='cart'),
        ),
    ]
