# Generated by Django 4.2.3 on 2023-08-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_fontsize_postcardforflower_titleonball'),
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_cart_for_flower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.postcardforflower', verbose_name='Надпись на открытке')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('title_on_ball', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.titleonball', verbose_name='Надпись на шаре')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
