# Generated by Django 4.2.3 on 2023-09-02 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_address', models.CharField(max_length=150, verbose_name='Название филиала')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='TypeOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип заказа',
                'verbose_name_plural': 'Типы заказа',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('as_soon_as_possible', models.BooleanField(default=False, verbose_name='Как можно скорее')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания заказа')),
                ('order_date_time', models.DateTimeField(verbose_name='Дата и время забора заказа')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('apartment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дом/квартира')),
                ('floor_and_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Этаж и код от домофона')),
                ('additional_to_order', models.CharField(blank=True, max_length=200, null=True, verbose_name='Доп инфо к заказу')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='cart.cartitem')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.filial', verbose_name='Филиал')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.transport', verbose_name='Транспорт')),
                ('type_of_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.typeoforder', verbose_name='Вид заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
