# Generated by Django 4.2.3 on 2023-08-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_banners_options_alter_banners_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='category_id',
            field=models.CharField(default=1, max_length=700, verbose_name='<property object at 0x0000014542041E90>'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banners',
            name='link',
            field=models.CharField(default='http://127.0.0.1:8000/api/v1/categories/', max_length=100),
        ),
    ]
