# Generated by Django 4.2.3 on 2023-09-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('cart', '0004_alter_order_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.transport', verbose_name='Транспорт'),
        ),
    ]
