# Generated by Django 4.2.3 on 2023-08-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_product_alter_banners_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='category_id',
            field=models.CharField(max_length=700, verbose_name='<property object at 0x0000022C79591D00>'),
        ),
    ]
