# Generated by Django 4.2.3 on 2023-07-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_asaas_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asaas',
        ),
    ]
