# Generated by Django 4.2.3 on 2023-08-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_banners_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='category_id',
            field=models.CharField(max_length=700, verbose_name='<property object at 0x000001EB2C091DF0>'),
        ),
    ]
