# Generated by Django 4.2.3 on 2023-09-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_banners_link_banners_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.CharField(blank=True, choices=[('Отменено', 'Отменено'), ('Доставлено', 'Доставлено'), ('В Обработке', 'В Обработке')], max_length=140, null=True),
        ),
    ]
