# Generated by Django 4.2.3 on 2023-09-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items_link',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000/api/v1/cart-items/', max_length=200, null=True),
        ),
    ]
