# Generated by Django 4.2.3 on 2023-09-03 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_order_cart_items_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_items_link',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.cartitem'),
            preserve_default=False,
        ),
    ]
