# Generated by Django 4.2.3 on 2023-09-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_remove_cartitem_order_remove_order_cart_items_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date_time',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата и время забора заказа'),
        ),
    ]
