# Generated by Django 4.2.3 on 2023-09-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, unique=True, verbose_name='ID админа')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('bot_owner', models.BooleanField(default=False, verbose_name='Владелец бота')),
            ],
            options={
                'verbose_name': 'Админ телеграм',
                'verbose_name_plural': 'Админ телеграма',
            },
        ),
    ]
