# Generated by Django 4.2.3 on 2023-07-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ШАРИКИ', 'ШАРИКИ'), ('ЦВЕТЫ', 'ЦВЕТЫ'), ('Cладкий подарок', 'Сладкий подарок'), ('Открытка', 'Открытка'), ('Другое', 'Другое')], max_length=200)),
            ],
        ),
    ]
