# Generated by Django 4.2.3 on 2023-09-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/logo/userlogo.png', null=True, upload_to='avatars/'),
        ),
    ]
