# Generated by Django 4.2.3 on 2023-08-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_date_of_birthday_user_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'verbose_name': 'Сброс пароля', 'verbose_name_plural': 'Сбросы паролей'},
        ),
        migrations.AlterModelOptions(
            name='userconfirm',
            options={'verbose_name': 'Код Верификации', 'verbose_name_plural': 'Коды Верификации'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=255, null=True),
        ),
    ]
