# Generated by Django 4.2.3 on 2023-09-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=125, null=True, verbose_name='id платежа в системе FreedomPay')),
                ('pg_salt', models.CharField(blank=True, max_length=125, null=True, verbose_name='salt(рандомное слово) платежа в системе FreedomPay')),
                ('pg_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('currency', models.CharField(blank=True, max_length=20, null=True, verbose_name='Валюта')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='метод оплаты')),
                ('payment_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Сумма')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='статус')),
                ('pg_card_pan', models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер карты')),
                ('pg_sig', models.CharField(blank=True, max_length=250, null=True, verbose_name='Подпись')),
                ('pg_result', models.CharField(blank=True, max_length=250, null=True, verbose_name='рузультат оплаты')),
                ('pg_user_phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='контактный номер тефона')),
                ('pg_user_contact_email', models.CharField(blank=True, max_length=250, null=True, verbose_name='контактный адрес Е-почты')),
                ('pg_failure_description', models.TextField(blank=True, null=True, verbose_name='Описание неудачной оплаты')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'db_table': 'transactions',
            },
        ),
    ]
