# Generated by Django 4.2.3 on 2023-09-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_filial_typeoforder_order'),
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='cart.order', verbose_name='Заказ/Корзина'),
        ),
    ]
